empresas_tecnologicas = [
    "Google",
    "Microsoft",
    "Apple",
    "Amazon",
    "Facebook (Meta)",
    "IBM",
    "Intel",
    "Cisco",
    "Oracle",
    "SAP",
    "NVIDIA",
    "Adobe",
    "Salesforce",
    "HP (Hewlett-Packard)",
    "Dell",
    "Sony",
    "Samsung",
    "Tesla",
    "Twitter",
    "LinkedIn (Microsoft)",
    "Uber",
    "Airbnb",
    "Netflix",
    "Spotify",
    "Dropbox"
]

razones_sociales = [
    "Tecnologías Innovadoras S.A.",
    "Soluciones Empresariales Ltda.",
    "Desarrollo Digital Internacional Inc.",
    "Consultores en Informática y Servicios S.R.L.",
    "Sistemas Avanzados para la Nube S.A.C.",
    "Ingeniería de Software Global S.C.",
    "Telecomunicaciones Integradas Ltd.",
    "Servicios Tecnológicos del Futuro S.A.",
    "Soluciones Creativas en Redes S.R.L.",
    "Innovación y Desarrollo Tecnológico Ltda.",
    "Especialistas en Sistemas Inteligentes Inc.",
    "Consultoría en Tecnología Avanzada S.C.",
    "Soluciones Informáticas Multinacionales S.A.S.",
    "Desarrollos Tecnológicos Innovadores S.A.C.",
    "Ingeniería de Datos y Automatización Ltd.",
    "Empresas Digitales Integradas Inc.",
    "Innovación en Tecnologías de la Información S.R.L.",
    "Servicios de Software y Hardware Ltda.",
    "Soluciones Empresariales Globales S.A.",
    "Consultoría Tecnológica Internacional Inc.",
    "Sistemas Inteligentes para Empresas S.C.",
    "Desarrollo de Aplicaciones Avanzadas S.A.",
    "Soluciones de Redes Empresariales Ltd.",
    "Empresas de Tecnología y Consultoría S.A.S."
]


condiciones_iva = [
    "Responsable Inscripto",
    "Monotributista",
    "Exento",
    "No Responsable",
    "Consumidor Final",
    "Responsable No Inscripto",
    "Agente de Retención",
    "Sujeto No Categorizado",
    "Sujeto Exento",
    "Sujeto No Alcanzado",
    "Sujeto Liberado",
    "Otro"
]

rubros_empresas_tecnologicas = [
    "Motor de Búsqueda",
    "Desarrollo de Software",
    "Hardware y Dispositivos",
    "Comercio Electrónico",
    "Redes Sociales",
    "Tecnologías de la Información",
    "Semiconductores",
    "Redes y Comunicaciones",
    "Base de Datos y Software Empresarial",
    "Sistemas de Gestión Empresarial",
    "Tarjetas Gráficas y Procesadores",
    "Diseño Gráfico y Multimedia",
    "Soluciones en la Nube",
    "Automatización y Consultoría",
    "Tecnologías de la Inteligencia Artificial",
    "Servicios de CRM",
    "Impresoras y Soluciones de Impresión",
    "Electrónica de Consumo",
    "Electrónica Automotriz",
    "Telecomunicaciones",
    "Comunicación y Colaboración Empresarial",
    "Automatización del Hogar y Dispositivos Conectados",
    "Entretenimiento Digital",
    "Streaming de Contenidos",
    "Almacenamiento de Datos y Servicios",
    "Plataformas de Desarrollo y Aplicaciones",
    "Tecnologías de Energía Renovable"
]


direcciones = [
    "123 Calle Principal, Ciudad Capital",
    "456 Avenida Tech, Distrito Tecnológico",
    "789 Camino Innovador, Pueblo Digital",
    "321 Boulevard de la Información, Metrópolis Digital",
    "567 Carretera Cibernética, Ciudad Electrónica",
    "890 Paseo del Software, Urbanización Tecnológica",
    "234 Plaza de las Redes, Villa Virtual",
    "876 Callejón del Futuro, Zona Digital",
    "543 Pasaje de la Innovación, Barrio Tecnológico",
    "210 Rincón de la Tecnología, Sector Digital",
    "987 Sendero de la Programación, Ciudad Codificada",
    "654 Ruta de la Robótica, Pueblo Digitalizado",
    "321 Alameda del Algoritmo, Urbanización Cibernética",
    "876 Avenida de la Automatización, Ciudad Digital",
    "234 Paseo del Procesador, Barrio de la Informática",
    "543 Plaza de los Datos, Área Digital",
    "789 Calle de la Ciberseguridad, Distrito Electrónico",
    "432 Rincón de la Realidad Virtual, Zona Tecnológica",
    "210 Pasaje de la Programación, Metrópolis Digital",
    "987 Paseo del Pixel, Ciudad Virtual",
    "654 Camino de la Computación, Urbanización Digital",
    "123 Avenida de la Inteligencia Artificial, Ciudad Tecnológica",
    "876 Plaza del Proyecto, Área Digitalizada",
    "567 Ruta del Desarrollo, Barrio Innovador",
    "890 Callejuela de la Innovación, Zona Electrónica"
]


nombres_proyectos_tecnologicos = [
    "Proyecto Quantum",
    "Innovación Digital",
    "Sistema Inteligente de Gestión",
    "Plataforma de Realidad Virtual",
    "Redes Cibernéticas Avanzadas",
    "Proyecto Aurora",
    "Automatización Total",
    "Ecosistema Blockchain",
    "Ingeniería de Datos en Tiempo Real",
    "Proyecto Helix: Genómica Avanzada",
    "Sistema de Seguridad Bioinformática",
    "Desarrollo de Drones Autónomos",
    "Plataforma de Aprendizaje Automático",
    "Red de Energía Renovable",
    "Proyecto Nebula: Exploración Espacial",
    "Simulador Cuántico",
    "Internet de las Cosas Industrial",
    "Sistema de Procesamiento de Lenguaje Natural",
    "Plataforma de Servicios en la Nube",
    "Proyecto Cyberspace",
    "Innovación en Movilidad Eléctrica",
    "Inteligencia Artificial para la Salud",
    "Proyecto Synthetics: Desarrollo de Materiales",
    "Sistema de Monitorización Global",
    "Realidad Aumentada en Educación",
    "Proyecto Stellar: Exploración del Universo",
    "Ciencia de Datos Aplicada",
    "Hologramas Interactivos",
    "Plataforma de Telemedicina",
    "Innovación en Energía Solar"
]


nombres_equipos = [
    "Equipo Innovación Tech",
    "CyberElite",
    "DreamTeam Coders",
    "Quantum Squad",
    "Data Mavericks",
    "Tech Explorers",
    "Code Wizards",
    "Ingeniería del Futuro",
    "Digital Pioneers",
    "Tech Titans",
    "Byte Benders",
    "Data Dynamos",
    "InnoVision Team",
    "CodeCrafters",
    "NubeXplorers",
    "AI Avengers",
    "Robotics R&D Crew",
    "Tech Fusion",
    "EcoInnovators",
    "CyberGuardians",
    "Smart Creators",
    "Infinite Loopers",
    "TechNinjas",
    "Quantum Quotients",
    "CodeStorm Team"
]


nombres_personas_random = [
    "Juan Martínez",
    "Laura Rodríguez",
    "Carlos Sánchez",
    "Ana Gómez",
    "Diego Pérez",
    "María González",
    "Sergio Díaz",
    "Valeria López",
    "Javier Herrera",
    "Natalia Fernández",
    "Alejandro Ramírez",
    "Isabel Torres",
    "Ricardo Medina",
    "Camila Ríos",
    "Luis Vargas",
    "Gabriela Morales",
    "Andrés Castro",
    "Daniela Ortega",
    "Martín Silva",
    "Carmen Jiménez",
    "Esteban Ruiz",
    "Carolina Núñez",
    "Miguel Mendoza",
    "Adriana Chávez"
]

grados_estudios = [
    "Educación Básica Incompleta",
    "Educación Básica Completa",
    "Bachillerato",
    "Técnico Superior",
    "Licenciatura",
    "Maestría",
    "Doctorado",
    "Postdoctorado",
    "Estudios Técnicos",
    "Formación Profesional",
    "Cursos y Certificaciones"
]


tecnologias_programacion = [
    "Python",
    "JavaScript",
    "Java",
    "C#",
    "C++",
    "Ruby",
    "Swift",
    "Kotlin",
    "Go",
    "TypeScript",
    "PHP",
    "Rust",
    "Objective-C",
    "Scala",
    "Haskell",
    "Perl",
    "Shell Scripting",
    "R",
    "Dart",
    "Lua",
    "Groovy",
    "Clojure",
    "F#",
    "HTML/CSS",
    "SQL",
    "Bash",
    "Assembly",
    "VHDL",
    "Verilog",
    "MATLAB",
    "Raspberry Pi",
    "Arduino",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring",
    "Express.js",
    "Ruby on Rails",
    "Laravel"
]

areas_de_trabajo = [
    "Consultoría Estratégica",
    "Desarrollo de Software",
    "Ingeniería de Datos",
    "Analítica y Ciencia de Datos",
    "Consultoría Financiera",
    "Recursos Humanos",
    "Gestión de Proyectos",
    "Ciberseguridad",
    "Diseño de Experiencia de Usuario (UX/UI)",
    "Consultoría Legal y Regulatoria",
    "Marketing Digital",
    "Transformación Digital",
    "Innovación y Desarrollo",
    "Gestión de Riesgos",
    "Servicios de Nube y Infraestructura",
    "Estrategias de Negocios Internacionales",
    "Optimización de Procesos",
    "Gestión del Cambio",
    "Desarrollo Organizacional",
    "Evaluación de Tecnologías Emergentes",
    "Consultoría Ambiental y Sostenibilidad",
    "Consultoría en Educación y Formación",
    "Servicios de Outsourcing",
    "Gestión de Relaciones con Clientes (CRM)",
    "Consultoría en Salud y Bienestar Laboral"
]
