USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Google', 99079748089, 'Exento', 'Desarrollo de Software', '210 Rincón de la Tecnología, Sector Digital',10);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Microsoft', 17479885902, 'No Responsable', 'Entretenimiento Digital', '321 Boulevard de la Información, Metrópolis Digital',4);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Apple', 88485663680, 'Monotributista', 'Entretenimiento Digital', '543 Pasaje de la Innovación, Barrio Tecnológico',4);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Amazon', 90892059772, 'Sujeto No Categorizado', 'Entretenimiento Digital', '789 Calle de la Ciberseguridad, Distrito Electrónico',13);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Facebook (Meta)', 73422079668, 'Sujeto Liberado', 'Hardware y Dispositivos', '234 Plaza de las Redes, Villa Virtual',9);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('IBM', 58374287872, 'Exento', 'Entretenimiento Digital', '567 Ruta del Desarrollo, Barrio Innovador',3);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Intel', 27118236988, 'Sujeto No Categorizado', 'Tecnologías de Energía Renovable', '890 Callejuela de la Innovación, Zona Electrónica',11);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Cisco', 30431706863, 'Sujeto No Categorizado', 'Diseño Gráfico y Multimedia', '876 Callejón del Futuro, Zona Digital',8);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Oracle', 12030440268, 'Sujeto Exento', 'Automatización del Hogar y Dispositivos Conectados', '321 Alameda del Algoritmo, Urbanización Cibernética',9);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('SAP', 99771219108, 'Sujeto Exento', 'Tecnologías de la Información', '890 Callejuela de la Innovación, Zona Electrónica',1);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('NVIDIA', 26925170418, 'Agente de Retención', 'Base de Datos y Software Empresarial', '987 Sendero de la Programación, Ciudad Codificada',19);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Adobe', 47132091536, 'Responsable No Inscripto', 'Automatización y Consultoría', '876 Avenida de la Automatización, Ciudad Digital',2);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Salesforce', 97549328736, 'Consumidor Final', 'Automatización y Consultoría', '654 Camino de la Computación, Urbanización Digital',20);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('HP (Hewlett-Packard)', 24079853842, 'Sujeto Exento', 'Electrónica Automotriz', '543 Pasaje de la Innovación, Barrio Tecnológico',9);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Dell', 77773333735, 'Agente de Retención', 'Servicios de CRM', '987 Sendero de la Programación, Ciudad Codificada',13);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Sony', 58129109364, 'Sujeto Exento', 'Servicios de CRM', '543 Pasaje de la Innovación, Barrio Tecnológico',8);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Samsung', 17660987151, 'Sujeto No Categorizado', 'Hardware y Dispositivos', '123 Avenida de la Inteligencia Artificial, Ciudad Tecnológica',7);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Tesla', 59242807612, 'Responsable Inscripto', 'Almacenamiento de Datos y Servicios', '456 Avenida Tech, Distrito Tecnológico',20);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Twitter', 26243658694, 'Otro', 'Motor de Búsqueda', '890 Paseo del Software, Urbanización Tecnológica',2);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('LinkedIn (Microsoft)', 41583783941, 'Responsable Inscripto', 'Tecnologías de la Información', '210 Pasaje de la Programación, Metrópolis Digital',2);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Uber', 68591829672, 'Otro', 'Motor de Búsqueda', '321 Boulevard de la Información, Metrópolis Digital',1);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Airbnb', 68849347320, 'Sujeto No Alcanzado', 'Streaming de Contenidos', '321 Alameda del Algoritmo, Urbanización Cibernética',1);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Netflix', 84079704708, 'Sujeto Liberado', 'Hardware y Dispositivos', '890 Callejuela de la Innovación, Zona Electrónica',13);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Spotify', 92877906835, 'Sujeto Liberado', 'Base de Datos y Software Empresarial', '543 Plaza de los Datos, Área Digital',9);
USE consultora;
INSERT INTO Cliente(nombre, cuil_cuit, razon_social, rubro, direccion, antiguedad) VALUES ('Dropbox', 74894215668, 'Agente de Retención', 'Tecnologías de la Inteligencia Artificial', '876 Plaza del Proyecto, Área Digitalizada',7);
